/*
 * This settings file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * In a single project build this file can be empty or even removed.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/4.3/userguide/multi_project_builds.html
 */
rootProject.name = 'smartthings-sdk'

include 'smartapp-core'
include 'smartapp-guice'
include 'smartapp-spring'
include 'smartapp-contextstore-dynamodb'
include 'smartthings-client'
include 'examples:kotlin-smartapp'
include 'examples:java-springboot-smartapp'
include 'examples:java-ratpack-guice-smartapp'
include 'examples:java-lambda-smartapp'
