# This is a basic workflow to help you get started with Actions

name: circleci/ruby

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: circleci
    - run: bundle install
           bundle exec rake db:schema:load
           bundle exec rspec spec
           bundle exec cucumber
